# Generated by Django 2.0.5 on 2018-09-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=2000)),
                ('modelo', models.CharField(max_length=15)),
                ('cor', models.CharField(max_length=15)),
                ('capacidade', models.IntegerField(max_length=50)),
                ('disponivel', models.BooleanField()),
            ],
        ),
    ]
