# Generated by Django 2.0.5 on 2018-09-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('cpf', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
