# Generated by Django 2.0.5 on 2018-09-29 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendarConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=2000)),
                ('hora_consulta', models.TimeField(default=0)),
                ('data', models.DateField()),
                ('tipo_de_consulta', models.CharField(max_length=2000)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Cidade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Paciente')),
            ],
        ),
    ]
