# Generated by Django 2.0.5 on 2018-09-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_agendarconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendarconsulta',
            name='hora_consulta',
            field=models.TimeField(),
        ),
    ]
