# Generated by Django 2.0.5 on 2018-09-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20180929_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendarconsulta',
            name='hora_consulta',
        ),
    ]
