# Generated by Django 2.0.5 on 2018-09-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_capacidadeveiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacidadeveiculo',
            name='Veiculo',
        ),
        migrations.RemoveField(
            model_name='capacidadeveiculo',
            name='agenda',
        ),
        migrations.DeleteModel(
            name='CapacidadeVeiculo',
        ),
    ]
