# Generated by Django 2.0.5 on 2018-09-29 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20180929_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlocarVeiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateField()),
                ('alocado', models.BooleanField()),
                ('qtd_cabe', models.IntegerField()),
                ('Veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Veiculo')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.AgendarConsulta')),
            ],
        ),
    ]
