# Generated by Django 2.0.5 on 2018-09-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alocarveiculos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alocarveiculos',
            old_name='Veiculo',
            new_name='veiculo',
        ),
    ]
